-- Utökning av Begrepp för drömtolkning: religiös/mytisk/symbolisk kontext i Beskrivning (ingen schemaändring).
-- Idempotent: INSERT IGNORE vid dubblett av Ord.

INSERT IGNORE INTO Begrepp (Ord, Beskrivning) VALUES
('ängel', 'Lins: kristen/mystisk, jungiansk skyddsarketyp. Funktion i dröm: budbärare, beskyddare, väktare vid tröskel, påminnelse om något större. Livsaxlar: tillit, kallelse, sårbarhet, överlämnande. Formulering: kan i en kristen-symbolisk läsning påminna om budskap eller närvaro — aldrig som bevis om faktiska väsen.'),
('ärkeängel', 'Lins: judisk/kristen ängeltradition. Funktion: hög auktoritet i det symboliska rummet, gränsvakt, beskärande av kaos. Livsaxlar: moralisk press, skydd, skuld/lättnad. Formulering: figuren kan i religiös symbolik *likna* en ärkeängel — inte identifieras dogmatiskt.'),
('riddare', 'Lins: medeltida/kristen/mytisk. Funktion: disciplin, lojalitet, prövning, skydd av det inre barnet, väpnad gräns. Livsaxlar: mod, plikt, skugga (hårdhet). Ordet "riddare" beskriver roll — inte historisk person.'),
('kung', 'Lins: arketyp makt/ordning, hermetisk "kunglig princip" som allegori. Funktion: auktoritet inåt eller utåt, lag inom psyket. Livsaxlar: kontroll, ansvar, skam kring makt.'),
('drottning', 'Lins: arketyp omsorg, suveränitet, gränssättning. Funktion: ordnande kraft, värdighet, ibland kyla. Livsaxlar: relation till eget värde och gränser.'),
('moder', 'Lins: korsande traditioner (stor moder, jungiansk moderarketyp). Funktion: näring, hållande, kvävande eller läkande. Livsaxlar: anknytning, sorg, omstrukturering av omsorg.'),
('fader', 'Lins: auktoritet, lag, skydd eller dom. Funktion: ramläggare, domare, frånvarande beskyddare. Livsaxlar: trygghet, rädsla för bedömning.'),
('barn', 'Lins: jungianskt själsligt barn, existentiellt oskuld. Funktion: sårbart centrum, framtida potential. Livsaxlar: sårbarhet, healing, innerlig längtan.'),
('skuggfigur', 'Lins: jungiansk skugga, dramatisk "främmande". Funktion: bortträngt, okänd del, vittne, förföljare. Livsaxlar: skam, integration, rädsla.'),
('vägvisare', 'Lins: mytisk/hermetisk. Funktion: ledsagning utan tvång, ledtråd. Livsaxlar: tillit till egen riktning.'),
('väktare', 'Lins: tröskelväktare (myt/esoterik). Funktion: stopp, prövning, skydd av heligt rum. Livsaxlar: gränser, mod att passera.'),
('demon', 'Lins: religiös litteratur som *språk* för det förskjutna — inte som ontologisk sanning. Funktion: skräck, frestelse, splittrad drift. Livsaxlar: skam, kamp, integration. Formulering: kan i en symbolisk läsning *fungera som* en demonisk gestalt — inte "bevis" om ondska.'),
('helig gestalt', 'Lins: komparativ religion. Funktion: helig närvaro, kallelse, skräckblandad vördnad. Livsaxlar: existentiell öppning, överlämnande.'),
('budbärare', 'Lins: biblisk/mythisk. Funktion: nyhet, uppmaning, varning utan detalj. Livsaxlar: förändring, budskap man inte velat höra.'),
('präst', 'Lins: kristen/judisk struktur. Funktion: medlare, tolkare av norm, ritual. Livsaxlar: skuld, bot, gemenskap.'),
('munk', 'Lins: buddhistisk/kristen askes. Funktion: avskalning, disciplin, inre lyssnande. Livsaxlar: ensamhet, sökande, tystnad.'),
('gudinna', 'Lins: hinduisk/grekisk/nordisk som *språk*. Funktion: livgivande eller förtärande aspekt av det heliga. Livsaxlar: kreativitet, kroppslighet, vrede.'),
('gudagestalt', 'Lins: komparativ; aldrig identifiera med specifik teologi som fakta. Funktion: övermänsklig ram, kallelse eller dom. Livsaxlar: ödmjukhet inför det större, rädsla för dom.'),
('drake', 'Lins: öst/asiatisk, europeisk, alkemisk (uroboros som allegori). Funktion: hot, skattväktare, urkraft, bärare, tröskel. Livsaxlar: rädsla, kraft, integration av aggressiv energi. Undvik tom "mystik" — beskriv *vad draken gör* i scenen.'),
('orm', 'Lins: biblisk, hinduisk (kundalini som *möjlig* association), medicinsk symbolik som metafor. Funktion: dold linje, förgiftning/helande, slingrande rörelse. Livsaxlar: sexualitet, rädsla, förnyelse.'),
('duva', 'Lins: kristen fredsbudbärare, jungiansk mildhet. Funktion: budskap, lättnad, andetag. Livsaxlar: försoning, sorgens lättande.'),
('lejon', 'Lins: judisk/heraldisk, solmyt. Funktion: majestät, hot, mod. Livsaxlar: självrespekt, ilska.'),
('lamm', 'Lins: kristen offermetafor som *språk* — inte dogm. Funktion: sårbar renhet, offerroll. Livsaxlar: ödmjukhet, utsatthet.'),
('elefant', 'Lins: buddhistisk/hinduisk (Ganesha som *möjlig* association, aldrig fastslå identitet). Funktion: minne, tyngd, vägen öppnas. Livsaxlar: uthållighet, sorg som bärs.'),
('örn', 'Lins: solfågel, hermetisk upphöjelse. Funktion: överblick, attack, frihet. Livsaxlar: distans, skärpa.'),
('varg', 'Lins: nordisk, folklig. Funktion: flock, hot, instinkt. Livsaxlar: tillhörighet, aggressiv drift.'),
('hjort', 'Lins: keltisk/nordisk skogsväsen. Funktion: skörhet, höjd, byte. Livsaxlar: sårbar skönhet, jagande inre krav.'),
('fisk', 'Lins: kristen symbol (ichthys) som litteratur, vattenexistens. Funktion: det dolda, näring, djup. Livsaxlar: känslodjup, tro som simmar under ytan.'),
('korp', 'Lins: nordisk, dödsfågel som arketyp. Funktion: bud om slut, minne, kråka. Livsaxlar: sorg, förmåga att se mörker.'),
('häst', 'Lins: shamanistisk, krigarkult. Funktion: bärare, flykt, viljekraft. Livsaxlar: kroppslig drivkraft, frihet.'),
('tjur', 'Lins: minoisk, alkemisk tjur som kraft. Funktion: styrka, sexualitet, stubbornhet. Livsaxlar: gränser, ilska.'),
('svärd', 'Lins: hermetisk urskiljning, biblisk "ordets svärd" som metafor. Funktion: delande, dom, skydd — eller oanvänt: outtalad auktoritet. Livsaxlar: sanning som skär, konflikt.'),
('stav', 'Lins: hermetisk/magisk som allegori. Funktion: auktoritet, riktning, stöd. Livsaxlar: ledarskap över sig själv.'),
('nyckel', 'Lins: kristen (Petri nycklar) som *språk*, psykologisk öppning. Funktion: tillträde, låsning. Livsaxlar: ansvar för vad som öppnas.'),
('krona', 'Lins: sakral kungadömme, själens suveränitet. Funktion: värdighet, börda. Livsaxlar: självrespekt, skuld kring ansvar.'),
('ring', 'Lins: keltisk/ Tolkien-influerad kulturminne, alkemisk cirkel. Funktion: förbund, oändlighet, boja. Livsaxlar: trohet, bundenhet.'),
('bok', 'Lins: judisk/kristen skrift, hermetiska tablåer. Funktion: lag, hemlighet, studie. Livsaxlar: behov av mening, skuld inför regler.'),
('sigill', 'Lins: esoterisk praktikhistoria som *kultur*, inte instruktion. Funktion: märke, avsikt förseglad. Livsaxlar: kontroll, önskan om garanterat resultat.'),
('sten', 'Lins: altare, grundsten, alkemisk "philosophers stone" som allegori. Funktion: tyngd, beständighet, prövning. Livsaxlar: förankring, hårdhet.'),
('onyx', 'Lins: smyckes/allegorisk tyngd. Funktion: mörker som bär skönhet, skydd. Livsaxlar: sorg som pryds.'),
('kors', 'Lins: kristen, förekommer i många kulturer som möte av axlar. Funktion: börda, centrum, uppoffring som metafor. Livsaxlar: skuld, uppriktelse — aldrig som påbud om tro.'),
('ros', 'Lins: rosenkorslik *litteraturhistoria*, mariansk symbolik. Funktion: sårbar skönhet, centrum. Livsaxlar: kärlek, smärta som öppnar.'),
('skål', 'Lins: graalmyt som *berättelse*, offerkärl. Funktion: mottagande, delande. Livsaxlar: gemenskap, tömning/fyllning.'),
('eld', 'Lins: rening i många traditioner, alkemisk calcinatio som allegori. Funktion: energi, rensning, förstörelse. Livsaxlar: ilska, passion — förankra i drömmens eld, inte abstrakt "förändring".'),
('lampa', 'Lins: hermetisk "lykta", psalmens olja. Funktion: medvetenhet i mörker, liten hållen sanning. Livsaxlar: hopp, uthållighet.'),
('spegel', 'Lins: alkemisk reflexion, sagosymbolik. Funktion: självbild, vändning, dubbel. Livsaxlar: skam, erkännande.'),
('korridor', 'Lins: psykogeografisk passage. Funktion: övergång, trång press, väntan. Livsaxlar: mellanläge, ångest.'),
('portal', 'Lins: mytisk tröskel, science fiction som metafor. Funktion: byte av värld, okänt rum. Livsaxlar: beslut, rädsla för det nya.'),
('tempel', 'Lins: hinduisk/buddhistisk/kristen helgedom som *arketyp*. Funktion: heligt rum inåt. Livsaxlar: sökande, skuld, vördnad.'),
('öken', 'Lins: biblisk, sufisk som *litteratur*. Funktion: prövning, tömning, klarhet. Livsaxlar: ensamhet, kallelse.'),
('berg', 'Lins: Moses, olympisk, buddhistisk höjd. Funktion: möte med större perspektiv, ansträngande stigning. Livsaxlar: överväldigande mål.'),
('torn', 'Lins: babel, isolerad höjd. Funktion: utsikt eller fångenskap. Livsaxlar: ensamhet, ambition.'),
('hav', 'Lins: kaosvatten, livmoder. Funktion: upplösning, djup. Livsaxlar: känslomässig överväldigande.'),
('skog', 'Lins: sagoskog, hjärtats mörker. Funktion: vilse, vildmark, möte med vilt. Livsaxlar: rädsla, instinkt.'),
('trädgård', 'Lins: paradis, odlad själ. Funktion: näring, gräns mot vildmark. Livsaxlar: skötsel av det inre.'),
('grav', 'Lins: kristen uppståndelsenarrativ som metafor, existentiell gräns. Funktion: avslut, möte med det förgångna. Livsaxlar: sorg, löslösning.'),
('avgrund', 'Lins: existentiell djup, mytisk klyfta. Funktion: hot om fall, möjlig öppning. Livsaxlar: rädsla, överlämnande.'),
('botten', 'Lins: nedstigning till grund (shamanistisk/jungiansk). Funktion: stopp, möte med grund. Livsaxlar: depression som bär budskap, förankring efter fall.'),
('panoramafönster', 'Lins: modern arkitektur som psykiskt rum. Funktion: utsikt, exponering, distans till världen. Livsaxlar: överblick, sårbar synlighet.'),
('huvud', 'Lins: "inne i huvudet" som metafor för reflexivitet. Funktion: introspektion, övertänkande. Livsaxlar: kontroll, upplösning av ego-gräns — förankra i drömmens scen.'),
('fall', 'Lins: klassisk drömtydning som *hypotes*, jungiansk nedstigning. Funktion: kontrollförlust, tyngdlag i psyket. Livsaxlar: rädsla, överlämnande.'),
('flykt', 'Lins: traumalitteratur, mytisk jagning. Funktion: undvikande, adrenal respons. Livsaxlar: hot, gränser.'),
('nedstigning', 'Lins: katabas grekisk, shamanistisk underjord. Funktion: möte med skugga. Livsaxlar: mod, depression som passage.'),
('uppstigning', 'Lins: mystisk stege, alkemisk sublimation som allegori. Funktion: lättnad, upphöjelse. Livsaxlar: hopp, andlig längtan — hypotetiskt.'),
('passage', 'Lins: liminalitet, tröskelantropologi. Funktion: varken här eller där. Livsaxlar: övergångsfaser.'),
('strid', 'Lins: inre kamp som yttre scen. Funktion: polaritet som söker integration. Livsaxlar: ilska, självkritik.'),
('dom', 'Lins: biblisk domsscen som *metafor* — inte teologisk dom. Funktion: självbedömning, skam. Livsaxlar: skuld, behov av nåd gentemot sig själv.'),
('rening', 'Lins: ritualhistoria, psykologisk "rengöring". Funktion: skilja väsentligt från oväsentligt. Livsaxlar: skam som vill tvättas bort, eller sund gräns.'),
('integration', 'Lins: jungiansk helhetsprocess. Funktion: delar som möts. Livsaxlar: mognad, acceptans.'),
('vitt', 'Lins: renhet, ljus, dödslakan — traditionsbundna associationer som *möjliga*. Funktion: tomhet eller klarhet. Livsaxlar: chock, frid — förankra i drömmens vitt.'),
('svart', 'Lins: skugga, natt, jord. Funktion: det outtalade. Livsaxlar: depression, mys, okänd potential.'),
('rött', 'Lins: passion, blod, varning. Funktion: intensitet, livskraft. Livsaxlar: ilska, sexualitet, gränssignal.'),
('blått', 'Lins: himmel, Maria-tradition som *kulturminne*, djup. Funktion: lugn eller kyla. Livsaxlar: längtan, melankoli.'),
('grönt', 'Lins: växt, islamisk paradisäng, hjärtchakra som *populärkultur*. Funktion: tillväxt, läkning. Livsaxlar: hopp, avundsjuka.'),
('guld', 'Lins: alkemisk slutstadium som allegori, helig glans. Funktion: värde, gudomlig glimt. Livsaxlar: självvärdighet, material längtan.'),
('violett', 'Lins: liturgisk färg, kronchakra som *metafor*. Funktion: gräns mellan jord och höjd. Livsaxlar: andlig sökning — hypotetiskt, aldrig auktoritativt.'),
('rosa', 'Lins: mild kärlek, gryning. Funktion: mjuk öppning. Livsaxlar: sårbar ömhet.');
